services:
  medical_backend:
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./.env:/app/.env
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  medical_ocr_worker:
    volumes:
      - ./app:/worker/app
      - ./.env:/worker/.env
      - hf_cache:/models/huggingface
    command:
      - uvicorn
      - app.ocr_worker.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8010"
      - --reload
